# Generated by Django 3.2.6 on 2021-08-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classnote', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
